# Cloudflare Worker 配置文件

name = "yiwanyang-chat"
main = "index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
name = "wechat-customer-service"
# 微信企业号配置
WECHAT_CORP_ID="ww6c44a5d33e931d7d"
WECHAT_KF_SECRET="x7iekSYipkK_RntHIIgrVELVlNtlSnGRPC-HKNZI3kY"
WECHAT_KF_TOKEN="l9lsmDG5M"
WECHAT_KF_ENCODING_AES_KEY="L9mYgECFm1yq3rXMEUa29i81GKxU3dofjb6jpLD1iXd"

# 加密服务配置（由于 CF Worker CRYPTO 兼容性问题，需要单独部署）
CRYPTO_SERVICE_URL="https://ywychat-666.workers.dev/callback"

# OpenAI API 配置
OPENAI_API_KEY="sk-PTOqIUfXYmAFOYhT03wqYplyPkbYdzSfa2ws0sJuoFe04cXl"
OPENAI_BASE_URL="https://api.aiywy.cn"
OPENAI_MODEL="sk-PTOqIUfXYmAFOYhT03wqYplyPkbYdzSfa2ws0sJuoFe04cXl"
OPENAI_TIMEOUT=30000
# OPENAI_ORGANIZATION=org-your-org-id
# OPENAI_PROJECT=proj-your-project-id

# 系统提示词配置
SYSTEM_PROMPT="your are helpful assistant, reply in chinese, and reply in plain text format, text length should be less than 10240 characters" 


# KV存储配置（用于持久化对话历史）
[[kv_namespaces]]
binding = "CONVERSATIONS"
id = "574671fc02ee4819abfac8f5e9e2a275"
preview_id = ""

# KV存储配置（用于消息处理状态跟踪）
[[kv_namespaces]]
binding = "MESSAGE_TRACKER"
id = "8a1e32c477fc4e5fa7faa470e5b5fb12"
preview_id = ""